{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Quick Run Block"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# import torch\n",
    "# from pytorch_lightning.callbacks import ModelCheckpoint\n",
    "\n",
    "# # Path to the problematic checkpoint\n",
    "# checkpoint_path = r\"c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\pre_trained_models\\reid\\dukemtmcreid_resnet50_256_128_epoch_120.ckpt\"\n",
    "\n",
    "# # Allow loading of ModelCheckpoint objects (since PyTorch 2.6 blocks this by default)\n",
    "# torch.serialization.add_safe_globals([ModelCheckpoint])\n",
    "\n",
    "# # Load the checkpoint safely\n",
    "# checkpoint = torch.load(checkpoint_path, map_location=\"cpu\", weights_only=False)\n",
    "\n",
    "# # Print out keys to inspect conflicting ones\n",
    "# print(\"Checkpoint keys:\", checkpoint.keys())\n",
    "\n",
    "# # Remove ModelCheckpoint states (if they exist)\n",
    "# keys_to_remove = [key for key in checkpoint.keys() if \"ModelCheckpoint\" in key]\n",
    "# for key in keys_to_remove:\n",
    "#     del checkpoint[key]\n",
    "\n",
    "# # Save the cleaned checkpoint\n",
    "# fixed_checkpoint_path = checkpoint_path.replace(\".ckpt\", \"_fixed.ckpt\")\n",
    "# torch.save(checkpoint, fixed_checkpoint_path)\n",
    "\n",
    "# print(f\"Fixed checkpoint saved to: {fixed_checkpoint_path}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Code"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\n",
      "Current working directory:  c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\ModelDevelopment\\experiments\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "from pathlib import Path\n",
    "import os\n",
    "\n",
    "sys.path.append(str(Path.cwd().parent.parent))\n",
    "print(str(Path.cwd().parent.parent))\n",
    "print(\"Current working directory: \", os.getcwd())\n",
    "\n",
    "from ModelDevelopment.CentralPipeline import CentralPipeline\n",
    "from ModelDevelopment.ImageBatchPipeline import ImageBatchPipeline\n",
    "from DataProcessing.DataPreProcessing import DataPaths"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Multithreaded Studies Research Findings\n",
    "- ThreadPoolExecutor works best for CentralPipeline pre-processing step (i.e. everything before run_pose)\n",
    "- Time taken to process one batch of 32 tracklets: 251 seconds => (251*32)/3600 = 2.35 hours ETA @ 200 images per batch cap, num_threads = 6x3 = 18\n",
    "- Note on the GPU_SEMAPHORE constant inside ImageFeatureTransformPipeline: this is always capped at 1 so we only offload 1 batch of images to the GPU\n",
    "- Since this gate is capped at 1, we can control the amount of data offloaded to the GPU via the image_batch_size param to CentralPipeline and only that\n",
    "- Since caching is implemented, you can try setting the gate to 2 for even faster results, and if the process crashes, keep restarting with use_cache=True"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2025-03-25 20:26:05 [INFO] DataPreProcessing initialized. Universe of available data paths:\n",
      "2025-03-25 20:26:05 [INFO] ROOT_DATA_DIR: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\extracted\n",
      "2025-03-25 20:26:05 [INFO] TEST_DATA_GT: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\extracted\\test\\test_gt.json\n",
      "2025-03-25 20:26:05 [INFO] TRAIN_DATA_GT: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\extracted\\train\\train_gt.json\n",
      "2025-03-25 20:26:05 [INFO] TEST_DATA_DIR: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\extracted\\test\\images\n",
      "2025-03-25 20:26:05 [INFO] TRAIN_DATA_DIR: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\extracted\\train\\images\n",
      "2025-03-25 20:26:05 [INFO] CHALLENGE_DATA_DIR: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\extracted\\challenge\\images\n",
      "2025-03-25 20:26:05 [INFO] PRE_TRAINED_MODELS_DIR: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\pre_trained_models\n",
      "2025-03-25 20:26:05 [INFO] REID_PRE_TRAINED: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\pre_trained_models\\reid\n",
      "2025-03-25 20:26:05 [INFO] STR_PRE_TRAINED: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\pre_trained_models\\str\n",
      "2025-03-25 20:26:05 [INFO] STR_MODEL: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\pre_trained_models\\str\\parseq_epoch=24-step=2575-val_accuracy=95.6044-val_NED=96.3255.ckpt\n",
      "2025-03-25 20:26:05 [INFO] REID_MODEL_1: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\pre_trained_models\\reid\\dukemtmcreid_resnet50_256_128_epoch_120.ckpt\n",
      "2025-03-25 20:26:05 [INFO] REID_MODEL_2: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\pre_trained_models\\reid\\market1501_resnet50_256_128_epoch_120.ckpt\n",
      "2025-03-25 20:26:05 [INFO] REID_CONFIG_YAML: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\pre_trained_models\\reid\\configs\\256_resnet50.yml\n",
      "2025-03-25 20:26:05 [INFO] RESNET_MODEL: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\pre_trained_models\\resnet\\legibility_resnet34_soccer_20240215.pth\n",
      "2025-03-25 20:26:05 [INFO] PROCESSED_DATA_OUTPUT_DIR: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\n",
      "2025-03-25 20:26:05 [INFO] PROCESSED_DATA_OUTPUT_DIR_TRAIN: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\train\n",
      "2025-03-25 20:26:05 [INFO] PROCESSED_DATA_OUTPUT_DIR_TEST: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\n",
      "2025-03-25 20:26:05 [INFO] PROCESSED_DATA_OUTPUT_DIR_CHALLENGE: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\challenge\n",
      "2025-03-25 20:26:05 [INFO] COMMON_PROCESSED_OUTPUT_DATA_TRAIN: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\train\\common_data\n",
      "2025-03-25 20:26:05 [INFO] COMMON_PROCESSED_OUTPUT_DATA_TEST: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\common_data\n",
      "2025-03-25 20:26:05 [INFO] COMMON_PROCESSED_OUTPUT_DATA_CHALLENGE: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\challenge\\common_data\n",
      "2025-03-25 20:26:05 [INFO] STREAMLINED_PIPELINE: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\n",
      "2025-03-25 20:26:05 [INFO] ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']\n",
      "2025-03-25 20:26:05 [INFO] Min tracklet: 0\n",
      "2025-03-25 20:26:05 [INFO] Max tracklet: 1210\n",
      "2025-03-25 20:26:05 [INFO] Using device: cuda\n",
      "2025-03-25 20:26:05 [INFO] ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']\n",
      "2025-03-25 20:26:05 [INFO] Min tracklet: 0\n",
      "2025-03-25 20:26:05 [INFO] Max tracklet: 1210\n"
     ]
    }
   ],
   "source": [
    "pipeline = CentralPipeline(\n",
    "  #tracklets_to_process_override=[\"1\"],\n",
    "  #num_tracklets=1210,\n",
    "  #num_images_per_tracklet=50,\n",
    "  input_data_path=DataPaths.TEST_DATA_DIR.value,\n",
    "  output_processed_data_path=DataPaths.PROCESSED_DATA_OUTPUT_DIR_TEST.value,\n",
    "  common_processed_data_dir=DataPaths.COMMON_PROCESSED_OUTPUT_DATA_TEST.value,\n",
    "  gt_data_path=DataPaths.TEST_DATA_GT.value,\n",
    "  single_image_pipeline=False,\n",
    "  display_transformed_image_sample=False, # NOTE: DO NOT USE. Code is parallelized so we cannot show images anymore. Code breaks, but first one will show if True.\n",
    "  num_image_samples=1,\n",
    "  use_cache=True, # Set to false if you encounter data inconsistencies.\n",
    "  suppress_logging=False,\n",
    "  \n",
    "  # --- PARALLELIZATION PARAMS --- These settings are optimal for an NVIDIA RTX 3070 Ti Laptop GPU.\n",
    "  num_workers=4,            # CRITICAL optimisation param. Adjust accordingly. 6\n",
    "  tracklet_batch_size=32,   # CRITICAL optimisation param. Adjust accordingly. 32\n",
    "  image_batch_size=200,     # CRITICAL optimisation param. Adjust accordingly. 200\n",
    "  num_threads_multiplier=3  # CRITICAL optimisation param. Adjust accordingly. 3. Interpretation: num_threads = num_workers * num_threads_multiplier\n",
    "  )"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### To Do\n",
    "- Investigate why last tracklet is not generated (1210 is skipped, probably something to do with batching)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2025-03-25 20:26:05 [INFO] Running the SoccerNet pipeline.\n",
      "2025-03-25 20:26:05 [INFO] Generating json for pose\n",
      "2025-03-25 20:26:05 [INFO] Reading legible & illegible results from cache (both global files exist).\n",
      "2025-03-25 20:26:05 [INFO] Used cached data for pose JSON\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "a56e6019dcd240438a172c510558cd6d",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Generating pose JSON:   0%|          | 0/1210 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2025-03-25 20:26:06 [INFO] Completed generating JSON for pose\n",
      "2025-03-25 20:26:06 [INFO] Detecting pose\n",
      "2025-03-25 20:26:06 [INFO] [910] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\910\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\910\\pose_results.json\n",
      "2025-03-25 20:26:06 [INFO] [1198] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1198\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1198\\pose_results.json\n",
      "2025-03-25 20:26:06 [INFO] [39] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\39\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\39\\pose_results.json\n",
      "2025-03-25 20:26:06 [INFO] [673] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\673\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\673\\pose_results.json\n",
      "2025-03-25 20:26:06 [INFO] [501] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\501\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\501\\pose_results.json\n",
      "2025-03-25 20:26:06 [INFO] [558] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\558\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\558\\pose_results.json\n",
      "2025-03-25 20:26:06 [INFO] [700] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\700\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\700\\pose_results.json\n",
      "2025-03-25 20:26:06 [INFO] [343] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\343\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\343\\pose_results.json\n",
      "2025-03-25 20:26:06 [INFO] [436] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\436\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\436\\pose_results.json\n",
      "2025-03-25 20:26:06 [INFO] [1121] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1121\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1121\\pose_results.json\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "16c354a91d4649a488a77f8b8983e123",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Running pose estimation:   0%|          | 0/836 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2025-03-25 20:26:06 [INFO] [113] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\113\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\113\\pose_results.json\n",
      "2025-03-25 20:26:06 [INFO] [996] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\996\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\996\\pose_results.json\n",
      "2025-03-25 20:26:17 [INFO] [673] loading annotations into memory...\n",
      "2025-03-25 20:26:17 [INFO] [673] Done (t=0.00s)\n",
      "2025-03-25 20:26:17 [INFO] [673] creating index...\n",
      "2025-03-25 20:26:17 [INFO] [673] index created!\n",
      "2025-03-25 20:26:17 [INFO] [673] \n",
      "2025-03-25 20:26:17 [INFO] [673] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\673\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\673\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:17 [INFO] [501] loading annotations into memory...\n",
      "2025-03-25 20:26:17 [INFO] [501] Done (t=0.00s)\n",
      "2025-03-25 20:26:17 [INFO] [501] creating index...\n",
      "2025-03-25 20:26:17 [INFO] [558] loading annotations into memory...\n",
      "2025-03-25 20:26:17 [INFO] [501] index created!\n",
      "2025-03-25 20:26:17 [INFO] [558] Done (t=0.00s)\n",
      "2025-03-25 20:26:17 [INFO] [501] \n",
      "2025-03-25 20:26:17 [INFO] [558] creating index...\n",
      "2025-03-25 20:26:17 [INFO] [501] The system cannot find the file specified.\n",
      "2025-03-25 20:26:17 [INFO] [558] index created!\n",
      "2025-03-25 20:26:17 [INFO] [501] Could Not Find C:\\Users\\colin\\miniconda3\\envs\\vitpose\\Library\\etc\\OpenCL\\vendors\\temp.txt\n",
      "2025-03-25 20:26:17 [INFO] [113] C:\\Users\\colin\\miniconda3\\envs\\vitpose\\Library\\etc\\OpenCL\\vendors\\temp.txt\n",
      "2025-03-25 20:26:17 [INFO] [700] loading annotations into memory...\n",
      "2025-03-25 20:26:17 [INFO] [558] \n",
      "2025-03-25 20:26:17 [INFO] [558] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\558\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\558\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:17 [INFO] [113] loading annotations into memory...\n",
      "2025-03-25 20:26:17 [INFO] [700] Done (t=0.00s)\n",
      "2025-03-25 20:26:17 [INFO] [501] \n",
      "2025-03-25 20:26:17 [INFO] [113] Done (t=0.00s)\n",
      "2025-03-25 20:26:17 [INFO] [700] creating index...\n",
      "2025-03-25 20:26:17 [INFO] [501] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\501\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\501\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:17 [INFO] [113] creating index...\n",
      "2025-03-25 20:26:17 [INFO] [700] index created!\n",
      "2025-03-25 20:26:17 [INFO] [113] index created!\n",
      "2025-03-25 20:26:17 [INFO] [700] \n",
      "2025-03-25 20:26:17 [INFO] [113] \n",
      "2025-03-25 20:26:17 [INFO] [700] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\700\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\700\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:17 [INFO] [113] The system cannot find the file specified.\n",
      "2025-03-25 20:26:17 [INFO] [113] \n",
      "2025-03-25 20:26:17 [INFO] [113] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\113\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\113\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:17 [INFO] [436] loading annotations into memory...\n",
      "2025-03-25 20:26:17 [INFO] [39] loading annotations into memory...\n",
      "2025-03-25 20:26:17 [INFO] [436] Done (t=0.00s)\n",
      "2025-03-25 20:26:17 [INFO] [39] Done (t=0.00s)\n",
      "2025-03-25 20:26:17 [INFO] [436] creating index...\n",
      "2025-03-25 20:26:17 [INFO] [39] creating index...\n",
      "2025-03-25 20:26:17 [INFO] [436] index created!\n",
      "2025-03-25 20:26:17 [INFO] [39] index created!\n",
      "2025-03-25 20:26:17 [INFO] [436] \n",
      "2025-03-25 20:26:17 [INFO] [39] \n",
      "2025-03-25 20:26:17 [INFO] [436] The system cannot find the file specified.\n",
      "2025-03-25 20:26:17 [INFO] [39] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\39\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\39\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:17 [INFO] [436] Could Not Find C:\\Users\\colin\\miniconda3\\envs\\vitpose\\Library\\etc\\OpenCL\\vendors\\temp.txt\n",
      "2025-03-25 20:26:17 [INFO] [436] \n",
      "2025-03-25 20:26:17 [INFO] [436] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\436\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\436\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:17 [ERROR] [673] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:17 [INFO] [1121] loading annotations into memory...\n",
      "2025-03-25 20:26:17 [INFO] [910] loading annotations into memory...\n",
      "2025-03-25 20:26:17 [INFO] [152] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\152\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\152\\pose_results.json\n",
      "2025-03-25 20:26:17 [INFO] [1121] Done (t=0.00s)\n",
      "2025-03-25 20:26:17 [INFO] [910] Done (t=0.00s)\n",
      "2025-03-25 20:26:17 [INFO] [1121] creating index...\n",
      "2025-03-25 20:26:17 [INFO] [910] creating index...\n",
      "2025-03-25 20:26:17 [INFO] [1121] index created!\n",
      "2025-03-25 20:26:17 [INFO] [910] index created!\n",
      "2025-03-25 20:26:17 [INFO] [1121] \n",
      "2025-03-25 20:26:17 [INFO] [910] \n",
      "2025-03-25 20:26:17 [INFO] [1121] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1121\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1121\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:17 [INFO] [910] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\910\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\910\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:17 [ERROR] [558] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:17 [INFO] [172] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\172\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\172\\pose_results.json\n",
      "2025-03-25 20:26:17 [ERROR] [501] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:17 [INFO] [544] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\544\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\544\\pose_results.json\n",
      "2025-03-25 20:26:17 [ERROR] [700] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:17 [INFO] [366] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\366\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\366\\pose_results.json\n",
      "2025-03-25 20:26:17 [ERROR] [436] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:17 [ERROR] [113] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:17 [INFO] [657] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\657\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\657\\pose_results.json\n",
      "2025-03-25 20:26:17 [INFO] [386] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\386\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\386\\pose_results.json\n",
      "2025-03-25 20:26:17 [ERROR] [39] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:17 [INFO] [991] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\991\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\991\\pose_results.json\n",
      "2025-03-25 20:26:17 [ERROR] [1121] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:17 [INFO] [199] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\199\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\199\\pose_results.json\n",
      "2025-03-25 20:26:17 [ERROR] [910] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:17 [INFO] [157] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\157\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\157\\pose_results.json\n",
      "2025-03-25 20:26:26 [INFO] [1198] loading annotations into memory...\n",
      "2025-03-25 20:26:26 [INFO] [1198] Done (t=0.00s)\n",
      "2025-03-25 20:26:26 [INFO] [1198] creating index...\n",
      "2025-03-25 20:26:26 [INFO] [1198] index created!\n",
      "2025-03-25 20:26:26 [INFO] [1198] load checkpoint from local path: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth\n",
      "2025-03-25 20:26:26 [INFO] [1198] \n",
      "2025-03-25 20:26:26 [INFO] [1198] C:\\Users\\colin\\miniconda3\\envs\\vitpose\\lib\\site-packages\\mmcv\\runner\\checkpoint.py:302: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "2025-03-25 20:26:26 [INFO] [1198] checkpoint = torch.load(filename, map_location=map_location)\n",
      "2025-03-25 20:26:26 [INFO] [1198] \n",
      "2025-03-25 20:26:26 [INFO] [1198] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1198\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1198\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:26 [ERROR] [1198] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:26 [INFO] [613] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\613\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\613\\pose_results.json\n",
      "2025-03-25 20:26:28 [INFO] [996] loading annotations into memory...\n",
      "2025-03-25 20:26:28 [INFO] [996] Done (t=0.00s)\n",
      "2025-03-25 20:26:28 [INFO] [996] creating index...\n",
      "2025-03-25 20:26:28 [INFO] [996] index created!\n",
      "2025-03-25 20:26:28 [INFO] [996] load checkpoint from local path: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth\n",
      "2025-03-25 20:26:28 [INFO] [996] \n",
      "2025-03-25 20:26:28 [INFO] [996] C:\\Users\\colin\\miniconda3\\envs\\vitpose\\lib\\site-packages\\mmcv\\runner\\checkpoint.py:302: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "2025-03-25 20:26:28 [INFO] [996] checkpoint = torch.load(filename, map_location=map_location)\n",
      "2025-03-25 20:26:28 [INFO] [996] \n",
      "2025-03-25 20:26:28 [INFO] [996] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\996\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\996\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:28 [INFO] [343] loading annotations into memory...\n",
      "2025-03-25 20:26:28 [INFO] [343] Done (t=0.00s)\n",
      "2025-03-25 20:26:28 [INFO] [343] creating index...\n",
      "2025-03-25 20:26:28 [INFO] [343] index created!\n",
      "2025-03-25 20:26:28 [INFO] [343] load checkpoint from local path: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth\n",
      "2025-03-25 20:26:28 [INFO] [343] \n",
      "2025-03-25 20:26:28 [INFO] [343] C:\\Users\\colin\\miniconda3\\envs\\vitpose\\lib\\site-packages\\mmcv\\runner\\checkpoint.py:302: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "2025-03-25 20:26:28 [INFO] [343] checkpoint = torch.load(filename, map_location=map_location)\n",
      "2025-03-25 20:26:28 [INFO] [343] \n",
      "2025-03-25 20:26:28 [INFO] [343] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\343\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\343\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:28 [ERROR] [996] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:28 [INFO] [883] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\883\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\883\\pose_results.json\n",
      "2025-03-25 20:26:28 [ERROR] [343] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:28 [INFO] [1102] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1102\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1102\\pose_results.json\n",
      "2025-03-25 20:26:31 [INFO] [991] loading annotations into memory...\n",
      "2025-03-25 20:26:31 [INFO] [991] Done (t=0.00s)\n",
      "2025-03-25 20:26:31 [INFO] [991] creating index...\n",
      "2025-03-25 20:26:31 [INFO] [991] index created!\n",
      "2025-03-25 20:26:31 [INFO] [991] \n",
      "2025-03-25 20:26:31 [INFO] [991] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\991\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\991\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:31 [ERROR] [991] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:31 [INFO] [549] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\549\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\549\\pose_results.json\n",
      "2025-03-25 20:26:32 [INFO] [1102] Traceback (most recent call last):\n",
      "2025-03-25 20:26:32 [INFO] [1102] File \"c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py\", line 33, in <module>\n",
      "2025-03-25 20:26:32 [INFO] [1102] from mmpose.apis import (inference_top_down_pose_model, init_pose_model,\n",
      "2025-03-25 20:26:32 [INFO] [1102] File \"c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\mmpose\\__init__.py\", line 2, in <module>\n",
      "2025-03-25 20:26:32 [INFO] [1102] import mmcv\n",
      "2025-03-25 20:26:32 [INFO] [1102] File \"C:\\Users\\colin\\miniconda3\\envs\\vitpose\\lib\\site-packages\\mmcv\\__init__.py\", line 4, in <module>\n",
      "2025-03-25 20:26:32 [INFO] [1102] from .fileio import *\n",
      "2025-03-25 20:26:32 [INFO] [1102] File \"C:\\Users\\colin\\miniconda3\\envs\\vitpose\\lib\\site-packages\\mmcv\\fileio\\__init__.py\", line 2, in <module>\n",
      "2025-03-25 20:26:32 [INFO] [1102] from .file_client import BaseStorageBackend, FileClient\n",
      "2025-03-25 20:26:32 [INFO] [1102] File \"C:\\Users\\colin\\miniconda3\\envs\\vitpose\\lib\\site-packages\\mmcv\\fileio\\file_client.py\", line 15, in <module>\n",
      "2025-03-25 20:26:32 [INFO] [1102] from mmcv.utils.misc import has_method\n",
      "2025-03-25 20:26:32 [INFO] [1102] File \"C:\\Users\\colin\\miniconda3\\envs\\vitpose\\lib\\site-packages\\mmcv\\utils\\__init__.py\", line 22, in <module>\n",
      "2025-03-25 20:26:32 [INFO] [1102] import torch\n",
      "2025-03-25 20:26:32 [INFO] [1102] File \"C:\\Users\\colin\\miniconda3\\envs\\vitpose\\lib\\site-packages\\torch\\__init__.py\", line 137, in <module>\n",
      "2025-03-25 20:26:32 [INFO] [1102] raise err\n",
      "2025-03-25 20:26:32 [INFO] [1102] OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading \"C:\\Users\\colin\\miniconda3\\envs\\vitpose\\lib\\site-packages\\torch\\lib\\cufft64_11.dll\" or one of its dependencies.\n",
      "2025-03-25 20:26:32 [INFO] [1102] \n",
      "2025-03-25 20:26:32 [INFO] [1102] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1102\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1102\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:32 [ERROR] [1102] Process returned non-zero exit code: 1\n",
      "2025-03-25 20:26:32 [INFO] [759] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\759\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\759\\pose_results.json\n",
      "2025-03-25 20:26:32 [INFO] [172] loading annotations into memory...\n",
      "2025-03-25 20:26:32 [INFO] [172] Done (t=0.00s)\n",
      "2025-03-25 20:26:32 [INFO] [172] creating index...\n",
      "2025-03-25 20:26:32 [INFO] [172] index created!\n",
      "2025-03-25 20:26:32 [INFO] [172] \n",
      "2025-03-25 20:26:32 [INFO] [172] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\172\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\172\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:32 [INFO] [386] loading annotations into memory...\n",
      "2025-03-25 20:26:32 [INFO] [386] Done (t=0.00s)\n",
      "2025-03-25 20:26:32 [INFO] [386] creating index...\n",
      "2025-03-25 20:26:32 [INFO] [386] index created!\n",
      "2025-03-25 20:26:32 [INFO] [386] \n",
      "2025-03-25 20:26:32 [INFO] [386] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\386\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\386\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:32 [ERROR] [172] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:32 [INFO] [65] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\65\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\65\\pose_results.json\n",
      "2025-03-25 20:26:32 [ERROR] [386] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:32 [INFO] [1174] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1174\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1174\\pose_results.json\n",
      "2025-03-25 20:26:37 [INFO] [157] loading annotations into memory...\n",
      "2025-03-25 20:26:37 [INFO] [157] Done (t=0.00s)\n",
      "2025-03-25 20:26:37 [INFO] [157] creating index...\n",
      "2025-03-25 20:26:37 [INFO] [157] index created!\n",
      "2025-03-25 20:26:37 [INFO] [157] load checkpoint from local path: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth\n",
      "2025-03-25 20:26:37 [INFO] [157] \n",
      "2025-03-25 20:26:37 [INFO] [157] The system cannot find the file specified.\n",
      "2025-03-25 20:26:37 [INFO] [157] Could Not Find C:\\Users\\colin\\miniconda3\\envs\\vitpose\\Library\\etc\\OpenCL\\vendors\\temp.txt\n",
      "2025-03-25 20:26:37 [INFO] [157] C:\\Users\\colin\\miniconda3\\envs\\vitpose\\lib\\site-packages\\mmcv\\runner\\checkpoint.py:302: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "2025-03-25 20:26:37 [INFO] [157] checkpoint = torch.load(filename, map_location=map_location)\n",
      "2025-03-25 20:26:37 [INFO] [157] \n",
      "2025-03-25 20:26:37 [INFO] [157] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\157\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\157\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:37 [INFO] [366] loading annotations into memory...\n",
      "2025-03-25 20:26:37 [INFO] [366] Done (t=0.00s)\n",
      "2025-03-25 20:26:37 [INFO] [366] creating index...\n",
      "2025-03-25 20:26:37 [INFO] [366] index created!\n",
      "2025-03-25 20:26:37 [INFO] [366] load checkpoint from local path: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth\n",
      "2025-03-25 20:26:37 [INFO] [366] \n",
      "2025-03-25 20:26:37 [INFO] [366] C:\\Users\\colin\\miniconda3\\envs\\vitpose\\lib\\site-packages\\mmcv\\runner\\checkpoint.py:302: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "2025-03-25 20:26:37 [INFO] [366] checkpoint = torch.load(filename, map_location=map_location)\n",
      "2025-03-25 20:26:37 [INFO] [366] \n",
      "2025-03-25 20:26:37 [INFO] [366] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\366\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\366\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:37 [ERROR] [157] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:37 [INFO] [1035] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1035\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1035\\pose_results.json\n",
      "2025-03-25 20:26:37 [ERROR] [366] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:37 [INFO] [1006] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1006\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\1006\\pose_results.json\n",
      "2025-03-25 20:26:43 [INFO] [883] C:\\Users\\colin\\miniconda3\\envs\\vitpose\\Library\\etc\\OpenCL\\vendors\\temp.txt\n",
      "2025-03-25 20:26:43 [INFO] [152] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\152\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\152\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:43 [INFO] [657] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\657\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\657\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:43 [INFO] [544] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\544\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\544\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:43 [INFO] [883] loading annotations into memory...\n",
      "2025-03-25 20:26:43 [INFO] [883] Done (t=0.00s)\n",
      "2025-03-25 20:26:43 [INFO] [883] creating index...\n",
      "2025-03-25 20:26:43 [INFO] [883] index created!\n",
      "2025-03-25 20:26:43 [INFO] [883] \n",
      "2025-03-25 20:26:43 [INFO] [883] The system cannot find the file specified.\n",
      "2025-03-25 20:26:43 [INFO] [883] \n",
      "2025-03-25 20:26:43 [INFO] [883] ERROR conda.cli.main_run:execute(125): `conda run python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\883\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\883\\pose_results.json` failed. (See above for error)\n",
      "2025-03-25 20:26:43 [ERROR] [883] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:43 [ERROR] [657] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:43 [ERROR] [544] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:43 [ERROR] [152] Process returned non-zero exit code: 4294967295\n",
      "2025-03-25 20:26:43 [INFO] [167] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\167\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\167\\pose_results.json\n",
      "2025-03-25 20:26:43 [INFO] [169] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\169\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\169\\pose_results.json\n",
      "2025-03-25 20:26:43 [INFO] [905] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\905\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\905\\pose_results.json\n",
      "2025-03-25 20:26:43 [INFO] [829] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\829\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\829\\pose_results.json\n",
      "2025-03-25 20:26:46 [INFO] [199] loading annotations into memory...\n",
      "2025-03-25 20:26:46 [INFO] [199] Done (t=0.00s)\n",
      "2025-03-25 20:26:46 [INFO] [199] creating index...\n",
      "2025-03-25 20:26:46 [INFO] [199] index created!\n",
      "2025-03-25 20:26:46 [INFO] [199] load checkpoint from local path: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth\n",
      "2025-03-25 20:26:46 [INFO] [199] 2025-03-25 20:26:44 [INFO] Wrote pose results to file: c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\199\\pose_results.json\n",
      "2025-03-25 20:26:46 [INFO] [199] \n",
      "2025-03-25 20:26:46 [INFO] [199] C:\\Users\\colin\\miniconda3\\envs\\vitpose\\lib\\site-packages\\mmcv\\runner\\checkpoint.py:302: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "2025-03-25 20:26:46 [INFO] [199] checkpoint = torch.load(filename, map_location=map_location)\n",
      "2025-03-25 20:26:46 [INFO] [199] \n",
      "2025-03-25 20:26:46 [INFO] [355] Running command: conda run -n vitpose python -u c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\StreamlinedPipelineScripts\\pose.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\configs\\body\\2d_kpt_sview_rgb_img\\topdown_heatmap\\coco\\ViTPose_huge_coco_256x192.py c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\pose\\ViTPose\\checkpoints\\vitpose-h.pth --img-root / --json-file c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\355\\pose_input.json --out-json c:\\Users\\colin\\OneDrive\\Desktop\\Jersey-Number-Recognition\\data\\SoccerNet\\jersey-2023\\processed_data\\test\\355\\pose_results.json\n"
     ]
    }
   ],
   "source": [
    "pipeline.run_soccernet(\n",
    "  run_soccer_ball_filter=False,\n",
    "  generate_features=False,\n",
    "  run_filter=False,\n",
    "  run_legible=False,\n",
    "  run_legible_eval=False,\n",
    "  run_pose=True,\n",
    "  run_crops=False,\n",
    "  run_str=False,\n",
    "  run_combine=False,\n",
    "  run_eval=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "UBC",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
